import React, { useCallback, useEffect, useState } from "react";
import api from "../lib/api";
import { useAuth } from "../lib/auth";

const adminRoles = new Set(["owner", "admin"]);
const operationalRoles = new Set(["owner", "admin", "operations", "dispatcher"]);
const labels = { required_checkpoints_unsatisfied:"Required checkpoints need review", profitability_snapshot_missing:"Profitability snapshot is missing", assignment_incomplete:"Assign both a driver and truck", material_snapshot_drift:"Load details changed; review the passport again", material_change_requires_reapproval:"A material load change requires reapproval", human_review_blocked:"Blocked by human review", approval_revoked:"Approval was revoked" };
function message(error) {
  const status=error?.response?.status; const detail=error?.response?.data?.detail;
  if (typeof detail === "string") return `${status || ""} ${detail}`.trim();
  if (detail?.blocking_reasons) return detail.blocking_reasons.map(x=>labels[x]||x).join("; ");
  return status ? `${status}: Passport operation failed` : "Passport service unavailable";
}
export default function LoadPassport({ loadId }) {
  const { user }=useAuth(); const [passport,setPassport]=useState(null); const [missing,setMissing]=useState(false); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const refresh=useCallback(()=>api.get(`/loads/${loadId}/passport`).then(r=>{setPassport(r.data);setMissing(false);setError("");}).catch(e=>{if(e?.response?.status===404){setMissing(true);setPassport(null);}else setError(message(e));}),[loadId]);
  useEffect(()=>{refresh();},[refresh]);
  const act=async(path,body={})=>{setBusy(true);setError("");try{await api.post(`/load-passports/${passport.id}/${path}`,body);await refresh();}catch(e){setError(message(e));}finally{setBusy(false);}};
  const checkpoint=async(cp,status)=>{setBusy(true);try{await api.put(`/load-passports/${passport.id}/checkpoints/${cp.type}`,{status,blocking:cp.blocking,reason_code:"",notes:"",evidence_document_ids:[],source:"manual"});await refresh();}catch(e){setError(message(e));}finally{setBusy(false);}};
  if(missing) return <section className="terminal-card p-4"><div className="kpi-label mb-2">Verified Load Passport</div><p className="text-xs text-zinc-500 mb-3">Internal administrative readiness record. It does not represent external verification.</p>{operationalRoles.has(user?.role)&&<button disabled={busy} onClick={async()=>{setBusy(true);try{await api.post(`/loads/${loadId}/passport`,{});await refresh();}catch(e){setError(message(e));}finally{setBusy(false);}}} className="text-xs bg-sky-500/20 text-sky-400 border border-sky-500/40 rounded px-3 py-1.5">Create passport</button>}{error&&<p className="text-xs text-red-400 mt-2">{error}</p>}</section>;
  if(!passport) return <section className="terminal-card p-4 text-xs text-zinc-500">Loading Load Passport…{error&&<span className="text-red-400 ml-2">{error}</span>}</section>;
  const ready=passport.readiness||{}; const auth=passport.pickup_authorization;
  return <section className="terminal-card p-4" data-testid="load-passport">
    <div className="flex flex-wrap items-center justify-between gap-2"><div><div className="kpi-label">Verified Load Passport</div><div className="font-mono text-xs text-zinc-500">{passport.id} · version {passport.version}</div></div><span className="font-mono text-xs uppercase border border-zinc-700 rounded px-2 py-1">{passport.status.replaceAll("_"," ")}</span></div>
    <p className="text-[11px] text-zinc-500 mt-2">Internal administrative checkpoints and evidence references only—no external identity, authority, insurance, or credential verification.</p>
    {(ready.blocking_reasons||[]).length>0&&<div className="mt-3 rounded border border-amber-500/30 bg-amber-500/10 p-2 text-xs text-amber-300">{ready.blocking_reasons.map(x=><div key={x}>• {labels[x]||x.replaceAll("_"," ")}</div>)}</div>}
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-2 mt-3">{passport.checkpoints.map(cp=><div key={cp.type} className="border border-zinc-800 rounded p-2"><div className="text-[10px] font-mono text-zinc-500 uppercase">{cp.type.replaceAll("_"," ")}</div><div className="flex items-center justify-between mt-1"><span className={`text-xs ${cp.status==="pass"||cp.status==="waived"?"text-emerald-400":cp.status==="fail"?"text-red-400":"text-amber-400"}`}>{cp.status}</span><select disabled={busy} value={cp.status} onChange={e=>checkpoint(cp,e.target.value)} className="bg-zinc-900 border border-zinc-800 text-[10px] rounded"><option value="pending">pending</option><option value="pass">pass</option><option value="fail">fail</option><option value="expired">expired</option></select></div></div>)}</div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-3 text-xs font-mono"><div><span className="text-zinc-500">Assignment</span><br/>{passport.assignment_snapshot?.driver_name||"No driver"} · {passport.assignment_snapshot?.truck_number||"No truck"} · {passport.assignment_snapshot?.trailer_identifier||"No trailer"}</div><div><span className="text-zinc-500">Profitability</span><br/>Net ${passport.profitability_snapshot?.estimated_net_profit ?? "—"} · {passport.profitability_snapshot?.estimated_margin_percentage ?? "—"}%</div><div><span className="text-zinc-500">Pickup authorization</span><br/>{auth?.status||"not issued"}{auth&&` · evidence ${auth.id}`}</div></div>
    <div className="flex flex-wrap gap-2 mt-3">{passport.status==="draft"&&operationalRoles.has(user?.role)&&<button disabled={busy} onClick={()=>act("submit")} className="text-xs border border-sky-500/40 text-sky-400 rounded px-2 py-1">Submit for review</button>}{passport.status==="blocked"&&operationalRoles.has(user?.role)&&<button disabled={busy} onClick={()=>act("return-to-review")} className="text-xs border border-sky-500/40 text-sky-400 rounded px-2 py-1">Return to review</button>}{passport.status==="review_pending"&&adminRoles.has(user?.role)&&<><button disabled={busy} onClick={()=>act("approve")} className="text-xs border border-emerald-500/40 text-emerald-400 rounded px-2 py-1">Approve</button><button disabled={busy} onClick={()=>act("reject",{reason:"Blocked by reviewer"})} className="text-xs border border-red-500/40 text-red-400 rounded px-2 py-1">Block</button></>}{passport.status==="approved"&&adminRoles.has(user?.role)&&<button disabled={busy} onClick={()=>act("authorize-pickup")} className="text-xs border border-emerald-500/40 text-emerald-400 rounded px-2 py-1">Authorize pickup</button>}{["approved","pickup_authorized"].includes(passport.status)&&adminRoles.has(user?.role)&&<button disabled={busy} onClick={()=>act("revoke",{reason:"Revoked by reviewer"})} className="text-xs border border-red-500/40 text-red-400 rounded px-2 py-1">Revoke</button>}<button disabled={busy} onClick={()=>act("refresh-profitability")} className="text-xs border border-zinc-700 rounded px-2 py-1">Refresh profitability</button></div>
    {error&&<p className="text-xs text-red-400 mt-2">{error}</p>}
  </section>;
}
