import React,{useCallback,useEffect,useState} from "react";
import api from "../lib/api";
import {useAuth} from "../lib/auth";
const admins=new Set(["owner","admin"]), operators=new Set(["owner","admin","operations","dispatcher"]);
const detail=e=>{const s=e?.response?.status,d=e?.response?.data?.detail;if(typeof d==="string")return `${s}: ${d}`;return s?`${s}: ${JSON.stringify(d||"Party verification operation failed")}`:"Party verification service unavailable";};
export default function PartyVerification({loadId}){
 const {user}=useAuth(),[item,setItem]=useState(null),[missing,setMissing]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const refresh=useCallback(()=>api.get(`/loads/${loadId}/party-verification-case`).then(r=>{setItem(r.data);setMissing(false);setError("");}).catch(e=>{if(e?.response?.status===404){setMissing(true);setItem(null);}else setError(detail(e));}),[loadId]); useEffect(()=>{refresh();},[refresh]);
 const post=async(path,body={})=>{setBusy(true);setError("");try{await api.post(`/party-verification-cases/${item.id}/${path}`,body);await refresh();}catch(e){setError(detail(e));}finally{setBusy(false);}};
 const review=async(domain,result="match")=>{setBusy(true);try{await api.put(`/party-verification-cases/${item.id}/reviews/${domain}`,{result,source:"manual",reason:"",evidence_document_ids:[]});await refresh();}catch(e){setError(detail(e));}finally{setBusy(false);}};
 if(missing)return <section className="terminal-card p-4"><div className="kpi-label">Party Verification & Risk</div><p className="text-[11px] text-zinc-500 my-2">Internal administrative review only. No live authority, policy, identity, domain, authenticity, or fraud-provider verification.</p>{operators.has(user?.role)&&<button disabled={busy} onClick={async()=>{setBusy(true);try{await api.post(`/loads/${loadId}/party-verification-case`,{});await refresh();}catch(e){setError(detail(e));}finally{setBusy(false);}}} className="text-xs border border-sky-500/40 text-sky-400 rounded px-2 py-1">Create case</button>}{error&&<p className="text-xs text-red-400 mt-2">{error}</p>}</section>;
 if(!item)return <section className="terminal-card p-4 text-xs text-zinc-500">Loading party verification…</section>;
 const risk=item.risk_summary||{};
 return <section className="terminal-card p-4" data-testid="party-verification"><div className="flex justify-between gap-2"><div><div className="kpi-label">Party Verification & Risk</div><div className="font-mono text-xs text-zinc-500">{item.id} · version {item.version}</div></div><span className="font-mono text-xs uppercase border border-zinc-700 rounded px-2 py-1">{item.status.replaceAll("_"," ")}</span></div>
 <p className="text-[11px] text-zinc-500 mt-2">Internal administrative consistency review only. The score is a workflow indicator, not a fraud probability. No external verification is performed.</p>
 <div className="grid grid-cols-1 md:grid-cols-4 gap-2 mt-3 text-xs"><div><span className="text-zinc-500">Broker</span><br/>{item.broker_snapshot?.name||"Missing"}</div><div><span className="text-zinc-500">Shipper</span><br/>{item.shipper_snapshot?.name||"Missing"}</div><div><span className="text-zinc-500">Carrier</span><br/>{item.carrier_snapshot?.name||"Incomplete"}</div><div><span className="text-zinc-500">Internal risk</span><br/>{risk.risk_level||"not evaluated"}{risk.risk_score!=null&&` · ${risk.risk_score}/100`}</div></div>
 <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-2 mt-3">{Object.values(item.reviews||{}).map(r=><div key={r.domain} className="border border-zinc-800 rounded p-2"><div className="text-[10px] uppercase font-mono text-zinc-500">{r.domain.replaceAll("_"," ")}</div><div className="text-xs mt-1">{r.result}</div>{["draft","review_pending","findings_open"].includes(item.status)&&<button disabled={busy} onClick={()=>review(r.domain)} className="text-[10px] text-sky-400 mt-1">mark internal match</button>}</div>)}</div>
 {(item.blocking_reasons||[]).length>0&&<div className="mt-3 border border-red-500/30 bg-red-500/10 p-2 text-xs text-red-300">{item.blocking_reasons.map(x=><div key={x}>• {x.replaceAll("_"," ")}</div>)}</div>}
 <div className="mt-3 text-xs"><span className="text-zinc-500">Findings / signals:</span> {(item.findings||[]).filter(x=>x.status==="open").length} open · {(item.risk_signals||[]).length} current</div>
 <div className="flex flex-wrap gap-2 mt-3">{item.status==="draft"&&operators.has(user?.role)&&<button disabled={busy} onClick={()=>post("submit")} className="text-xs border border-sky-500/40 text-sky-400 rounded px-2 py-1">Submit</button>}<button disabled={busy||item.status==="cleared"} onClick={()=>post("refresh")} className="text-xs border border-zinc-700 rounded px-2 py-1">Refresh snapshots</button><button disabled={busy||item.status==="cleared"} onClick={()=>post("evaluate")} className="text-xs border border-zinc-700 rounded px-2 py-1">Evaluate</button>{admins.has(user?.role)&&["review_pending","findings_open"].includes(item.status)&&<><button disabled={busy} onClick={()=>post("clear")} className="text-xs border border-emerald-500/40 text-emerald-400 rounded px-2 py-1">Clear internally</button><button disabled={busy} onClick={()=>post("block",{reason:"Blocked pending internal review"})} className="text-xs border border-red-500/40 text-red-400 rounded px-2 py-1">Block</button></>}{admins.has(user?.role)&&item.status==="cleared"&&<button disabled={busy} onClick={()=>post("revoke",{reason:"Internal clearance revoked"})} className="text-xs border border-red-500/40 text-red-400 rounded px-2 py-1">Revoke</button>}</div>{error&&<p className="text-xs text-red-400 mt-2">{error}</p>}</section>;
}
