import React,{useCallback,useEffect,useState} from "react";
import api from "../lib/api";
import {useAuth} from "../lib/auth";
const admins=new Set(["owner","admin"]),operators=new Set(["owner","admin","operations","dispatcher"]);
const vocabulary=["rate_confirmation_number","broker_name","total_rate","loaded_miles","commodity","weight","equipment_type","pickup_address","pickup_city","pickup_state","pickup_postal_code","pickup_date","pickup_time_start","delivery_address","delivery_city","delivery_state","delivery_postal_code","delivery_date","delivery_time_start","special_instructions"];
const numbers=new Set(["total_rate","loaded_miles","weight"]);
const msg=e=>`${e?.response?.status||503}: ${typeof e?.response?.data?.detail==="string"?e.response.data.detail:"Rate-confirmation operation failed"}`;
export default function RateConfirmationIntelligence({loadId,documents=[]}){
 const {user}=useAuth(),[items,setItems]=useState([]),[item,setItem]=useState(null),[form,setForm]=useState({}),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const refresh=useCallback(()=>api.get(`/loads/${loadId}/rate-confirmation-extractions`).then(r=>{setItems(r.data);setItem(x=>r.data.find(y=>y.id===x?.id)||r.data[0]||null);}).catch(e=>setError(msg(e))),[loadId]);
 useEffect(()=>{refresh();},[refresh]); useEffect(()=>setForm(item?.extracted_fields||{}),[item]);
 const run=async(method,path,body={})=>{setBusy(true);setError("");try{const r=await api[method](path,body);setItem(r.data);await refresh();}catch(e){setError(msg(e));}finally{setBusy(false);}};
 const create=()=>{const d=documents.find(x=>x.doc_type==="rate_con");return d?run("post",`/loads/${loadId}/rate-confirmation-extractions`,{document_id:d.id,source:"manual",extracted_fields:{},notes:""}):setError("404: Log a rate-confirmation document first");};
 const resolve=(d,decision)=>run("put",`/rate-confirmation-extractions/${item.id}/discrepancies/${d.id}`,{resolution:decision==="use_document_value"?"accepted_as_document":"accepted_as_load",decision,reason:""});
 return <section className="terminal-card p-4" data-testid="rate-confirmation-intelligence"><div className="flex justify-between gap-2"><div><div className="kpi-label">Rate Confirmation Intelligence</div><p className="text-[11px] text-zinc-500 mt-1">Human-reviewed structured evidence only. No live OCR, AI extraction, authenticity validation, or external broker/shipper verification.</p></div>{!item&&operators.has(user?.role)&&<button onClick={create} className="text-xs border border-sky-500/40 text-sky-400 rounded px-2">Create manual extraction</button>}</div>
 {item&&<><div className="flex gap-2 mt-3 text-xs font-mono"><span>{item.id}</span><span>rev {item.revision}</span><span className="text-amber-400">{item.status}</span><span>source {item.source}</span></div><div className="grid grid-cols-1 md:grid-cols-3 gap-2 mt-3">{vocabulary.map(f=><label key={f} className="text-[10px] text-zinc-500 uppercase">{f.replaceAll("_"," ")}<input disabled={item.status!=="draft"||busy} type={numbers.has(f)?"number":"text"} value={form[f]??""} onChange={e=>setForm({...form,[f]:numbers.has(f)&&e.target.value!==""?Number(e.target.value):e.target.value})} className="mt-1 w-full bg-zinc-950 border border-zinc-800 rounded p-1.5 text-xs text-zinc-200 normal-case"/></label>)}</div><div className="flex flex-wrap gap-2 mt-3">{item.status==="draft"&&operators.has(user?.role)&&<><button onClick={()=>run("put",`/rate-confirmation-extractions/${item.id}`,{extracted_fields:Object.fromEntries(Object.entries(form).filter(([,v])=>v!==""))})} className="text-xs border border-zinc-700 rounded px-2 py-1">Save</button><button onClick={()=>run("post",`/rate-confirmation-extractions/${item.id}/compare`)} className="text-xs border border-sky-500/40 text-sky-400 rounded px-2 py-1">Compare</button><button onClick={()=>run("post",`/rate-confirmation-extractions/${item.id}/submit`)} className="text-xs border border-sky-500/40 text-sky-400 rounded px-2 py-1">Submit</button></>}{["review_pending","discrepancies_found"].includes(item.status)&&admins.has(user?.role)&&<><button onClick={()=>run("post",`/rate-confirmation-extractions/${item.id}/accept`)} className="text-xs border border-emerald-500/40 text-emerald-400 rounded px-2 py-1">Accept</button><button onClick={()=>run("post",`/rate-confirmation-extractions/${item.id}/reject`,{reason:"Rejected by reviewer"})} className="text-xs border border-red-500/40 text-red-400 rounded px-2 py-1">Reject</button></>}{item.status==="rejected"&&operators.has(user?.role)&&<button onClick={()=>run("post",`/rate-confirmation-extractions/${item.id}/return-to-review`)} className="text-xs border border-sky-500/40 text-sky-400 rounded px-2 py-1">Return to review</button>}</div>{(item.discrepancies||[]).map(d=><div key={d.id} className={`border rounded p-2 text-xs mt-2 ${d.severity==="blocking"?"border-red-500/30":"border-amber-500/30"}`}><div>{d.type.replaceAll("_"," ")} · {d.severity} · {d.resolution_status}</div><div className="grid grid-cols-2 font-mono"><span>Load: {String(d.load_value??"—")}</span><span>Document: {String(d.document_value??"—")}</span></div>{d.resolution_status==="unresolved"&&admins.has(user?.role)&&<div className="flex gap-2 mt-1"><button onClick={()=>resolve(d,"keep_load_value")}>Keep load</button><button className="text-sky-400" onClick={()=>resolve(d,"use_document_value")}>Use document</button></div>}</div>)}{item.accepted_snapshot&&<div className="mt-3 border border-emerald-500/30 rounded p-2 text-xs">Accepted internal evidence · {item.accepted_snapshot.accepted_at}</div>}</>}
 {items.length>1&&<select className="mt-3 bg-zinc-950 text-xs" value={item?.id||""} onChange={e=>setItem(items.find(x=>x.id===e.target.value))}>{items.map(x=><option key={x.id} value={x.id}>rev {x.revision} · {x.status}</option>)}</select>}{error&&<p className="text-xs text-red-400 mt-2">{error}</p>}</section>;
}
